# Generated by Django 4.0.5 on 2022-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tags',
        ),
    ]
