# Generated by Django 4.0.5 on 2022-07-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_table_alter_tag_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
