# Generated by Django 4.0.5 on 2022-07-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_category_options_alter_product_options_and_more'),
        ('order', '0002_remove_order_price_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ManyToManyField(related_name='products', to='marketplace.product'),
        ),
    ]
