# Generated by Django 4.0.5 on 2022-07-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_category_options_alter_product_options_and_more'),
        ('order', '0003_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.ManyToManyField(related_name='prices', to='marketplace.product'),
        ),
    ]
