# Generated by Django 4.0.5 on 2022-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_quantity_alter_order_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
